### ISSUE TITLE
Error on create new Applicaction

### ISSUE THREAD

**Issue by silmeUsil0001** [sitmun/sitmun-admin-app#137]
**Describe the bug**
Error on create new Applicaction

**To Reproduce**
1. Go to 'Aplicació'
2. Check app 3 and press 'Duplicate button'
3. On the new forma, press save button
4. Even it is an internal app, URL must be filled (other existing internal applications has blank url)

![err4](https://github.com/sitmun/sitmun-admin-app/assets/6534787/27e93c02-5aca-4e84-a0f0-7f5da38a3990)

6. If this filed is filled wifth any link, press again button
7. See error

![err3](https://github.com/sitmun/sitmun-admin-app/assets/6534787/08494074-8598-46c6-9b0b-0d701d028282)

**Expected behavior**
A new app should be created with the same parameters as the initial one

**Comment by fjlopez** [comment]
**:warning:  Bug cannot be reproduced**

Missing step?


Mandatory *Url* is a legacy of SITMUN 2. This should be considered as a bug and fixed in the code and in the client. However:

- Duplicate of the external app  1 can be saved.
- Duplicate of the internal app 3 with mandatory *Url* equal to `ff` can be saved.
- Duplicate of the internal app 3 with mandatory *Url* equal to `ff` and same values as the screenshot can be saved. https://sitmun.github.io/admin-app/#/application/9/applicationForm 

**Suggested action:**
- @silmeUsil0001 try to reproduce the bug

**Comment by fjlopez** [comment]
- New bug created for improving the logic of the form: https://github.com/sitmun/sitmun-admin-app/issues/138
- Fixed behavior in the backend: https://github.com/sitmun/sitmun-backend-core/commit/54f8bd259f3dfee280b6abb90a7b6b89b1c08374
