### ISSUE TITLE
Root node from tree not sent properly by the API-REST

### ISSUE THREAD

**Issue by mvinent** [sitmun/sitmun-admin-app#147]
**Describe the bug**
The JSON received when calling API-REST does not include the root node from the tree properly. 
For example, in the administrator we have the tree configured as follows:
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/111d8809-61c8-43bf-9889-5e80da0dae1d)

And the JSON received is:
![image](https://github.com/sitmun/sitmun-admin-app/assets/45626106/190dd69c-1eda-4709-b7d2-11e85dffff56)

The attribute rootNode in the JSON should be the node "Root" from the administrator or an array of the nodes depending of the node "Root", but currently it is one of the nodes depending of the "Root" node. 
Also, the node 'chosen' to be root seems random or without a defined criteria.

**To Reproduce**
1. Go to administrator
2. Click on trees section
3. Select a tree to modify
4. Create more than one node under 'Root' node
5. Save configuration
6. Call API to get JSON response
7. See error

**Expected behavior**
The attribute rootNode from the JSON response should have a meaningful value, otherwise its useless. Ideally the 'Root' node from the administrator tree.

**Comment by fjlopez** [comment]
Bug confirmed. This bug belongs to https://github.com/sitmun/sitmun-backend-core. 

The logic assumes that a single root node (i.e. root) exists, but this is a false assumption. The node root in the administrator is virtual. To fix this issue this patch creates a virtual root node in the JSON response. 

Fixed with https://github.com/sitmun/sitmun-backend-core/commit/bb968a925bbc1e03ca664bf7f094719b846616b9.

@mvinent please validate this fix.
