### ISSUE TITLE
Config requests fails with 502 bad gateway

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-admin-app#190]
Some requests are failing at the start of the application of the sitmun-admin-app, the http code response is 502 bad gateway.

**To Reproduce:**

1. Clone the project:

`git clone --branch feature-4 --recurse-submodules https://github.com/sitmun/sitmun-application-stack.git`

2. Navigate to the project directory:

`cd sitmun-application-stack`

3. Check that the branch Updates of `sitmun-admin-app` is selected:

`git submodule status`
Must output a line that contains the string front/admin/sitmun-admin-app (remotes/origin/Updates)

4. Build the Docker image without using the cache:

`docker compose build --no-cache`

5. Run the Docker containers:

`docker compose up -d`

6. Go to `http://localhost:9000/admin`
7. Observe the following errors, that return 502 bad gateway: 

![image](https://github.com/user-attachments/assets/88e2be95-6085-41cc-8ac2-28d325aa243e)

**Context:**

In an efford to fix the angular material style errors mentioned in the ticket #185, we followed the procedure mentioned in the following ([page](https://v15.material.angular.io/guide/mdc-migration#2-run-the-migration-tool)). Once the `ng generate @angular/material:mdc-migration` command was done running all this errors have appeared and no other changes have been made.

**Comment by fjlopez** [comment]
In order to replicate your environment, after step 1 I will execute `git submodule update --remote --merge` to add to `sitmun-application-stack` today commits.

**Comment by fjlopez** [comment]
Issue unreproducible. Please, check your log messages in Docker related to the backend service to identify a local possible cause. 

**Steps Taken to reproduce the bug unsuccessfully**

1. **Docker Cleanup:** Removed all containers, images, volumes, and builds on my box using Docker Desktop.
2. **Repository Setup:** Cloned the repository and updated submodules to fetch the latest version of your commits:
     ```bash
     git clone --branch feature-4 --recurse-submodules https://github.com/sitmun/sitmun-application-stack.git
     git submodule update --remote --merge
     ```
3. **Execution:** Built the Docker images with no cache and then started the Docker containers in detached mode:
     ```bash
     docker compose build --no-cache
     docker compose up -d
     ```
4. **Service Verification:**. Verified that all services were in a healthy state by checking with `docker ps` after waiting approximately 30 seconds. This step ensure that the backend is ready to process requests.
5. **Access and Validation:**. Accessed the application at [http://localhost:9000/admin](http://localhost:9000/admin) and observed that all backend requests returned a status code of 200, as shown in the screenshot below:

   ![Backend Requests Status](https://github.com/user-attachments/assets/42158e27-58e7-4ddc-b2ee-f64ebdc58309)

**Test Environment:**
- Chrome 127.0.6533.72 (Official Build) (arm64)
- Sonoma 14.6
- Docker Desktop v4.33.0

**Comment by fjlopez** [comment]
I just verified that the problem is related to your local installation and is unrelated to the migration. 

**Additional Context and Reproduction Steps:**
To replicate the context faithfully, I assumed that the outcome of `ng generate @angular/material:mdc-migration` had not yet been pushed to GitHub. Consequently, I performed the following steps:

- Installed all node dependencies:
   ```bash
   cd front/admin/sitmun-admin-app
   npm ci
   ```
- Edited `package.json` to add a script named `migrated` that executes:
     ```json
     "migrate": "ng generate @angular/material:mdc-migration"
     ```
- Ran the migration script:
     ```bash
     npm run migrate
     ```
- Executed the migration for all directories and selected "All" for components to migrate.
- Navigated back to the root directory:
    ```bash
     cd ../../..
     ```
- Brought down the front-end services:
     ```bash
     docker compose down front
     ```
- Built the front-end Docker image with no cache to rebuild using the migrated files :
     ```bash
     docker build --no-cache front -t sitmun-application-stack-front
     ```
- Brought up the updated front-end service in detached mode:
     ```bash
     docker compose up front -d
     ```
- Accessed the application at http://localhost:9000/admin and again all backend responses work as expected
<img width="1629" alt="Captura de pantalla 2024-07-31 a las 12 01 24" src="https://github.com/user-attachments/assets/80530fdf-4bf7-4b63-a021-6d6d27852d13">

**Test Environment:**
- Browser: Chrome 127.0.6533.72 (Official Build) (arm64)

**Comment by fjlopez** [comment]
It seems likely that removing all related Docker containers, images, volumes, and builds and then rebuilding them might resolve the issue. However, before you proceed with this approach, I recommend checking the logs for the backend service to identify any potential causes of the problem.

Run `docker logs -f sitmun-application-stack-backend-1` (replace `sitmun-application-stack-backend-1` with the actual name of your backend container if it differs). Next, review the output for any error messages, warnings, or unusual behavior that might indicate the cause of the problem and post it here.

**Comment by albertcoro** [comment]
I have completed all the steps you mentioned also double checked with @gon-nexus and it appears is my local docker. I'll be working on it, thank you for your help
