### ISSUE TITLE
The useless 'Origen'  field in layer menu... but it's extraordinary potential.

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-admin-app#209]
**Describe the bug**
There is a field in the layer list menu (and also in the editing layer form) named 'Origen' with a unknown use. It does not exists in SITMUN 2 and I can't find anywhere why it has been created. The field appears in the layer list in the Layer menú.

On the other hand It would be helpful in the layer list to have a field showing the service where the layer belongs. 

**To Reproduce**
1. Go to SITMUN admin 
2. Click on 'Capes' menu
3. Look at the 'Origin' field and imagine what it would be if the service from which the layer originates was displayed instead.
4. Realize it would be much better.

**Expected behavior**
Display the service filed insteed. So replace the origen filed for the service. And make it clear why 'origen' exists.

**Screenshots**
The origen filed

![image](https://github.com/user-attachments/assets/b9ca445c-dc0f-4df4-a875-07d5d81b0299)

![image](https://github.com/user-attachments/assets/3fa89900-5f07-4a23-826e-590efa8e27d4)

**Comment by fjlopez** [comment]
The field `Origen` was originally introduced to meet the needs of DIBA for performing batch operations on a large set of related layers. The idea was to tag these layers with the same key, allowing batch changes to be applied across all of them. However, since batch operations were never implemented, this field remains unused.

The information regarding the service that acts as the source is stored in the `Servei` field.

**Comment by RicardCots** [comment]
Understood, then i'll open a new issue as a new funcionality, because it will be usefull to add Servei field to the layer list.

**Comment by RicardCots** [comment]
ok

**Comment by fjlopez** [comment]
Reformulated as #214
