### ISSUE TITLE
USER - Edition (stm_post)

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#52]
When deleting ALL roles from a territory in the Roles panel, the STM_POST table row (the user's position in the territory) should be automatically deleted for that territory, since the user does not have any access to that territory. You can see this behavior in SITMUN2_Adm.

**Comment by codinachssm** [comment]
@gon-nexus Had you developed any part of this functionality?
After discussion in the TC, we decided that it should not be deleted automatically, but that the system should notify the administrator that the user has no relationship with that territory, in case the administrator wants to delete the post entry for that territory-user.

**Comment by gon-nexus** [comment]
@codinachssm  
Excuse me! I had done what you said to me at the start of the issue, but I forgot to put it to "pending validation", right now if you delete all of the roles in the territory you delete the row in the STM_POST table, my question is, you want me to leave it like this or, instead of removing it, show a dialogue to inform the user, bear in mind that with this last way there will be no way to remove it from the STM_POST table, since the panel on the user screen is merely informative.

**Comment by codinachssm** [comment]
The TC's decision was not to delete the entry in the STM_POST table but to inform the user that he no longer has any relationship with that territory through the Permissions. BUT it must be possible to delete that STM_POST row manually from the administrator user interface.
