### ISSUE TITLE
ROLE - Missing relation table User-Territory

### ISSUE THREAD

**Issue by IDEmenorca** [sitmun/sitmun-admin-app#71]
The list of users and territories that have a role must be shown in Role and must be editable. The content of this component is similar to Permissions found in User and Territory forms.

**Comment by fjlopez** [comment]
@lucenasj this issue was in the `community` project due to an error; it belongs to `revisión interfaz`.

**Comment by lucenasj** [comment]
At the meeting on 27-01-2021, it was decided that the role screen would not handle the permissions, since with the new functionality of applying permissions to children/parents, we cannot know from the role screen whether we are as child role or parent role, and it was therefore decided that permission management would only do so from the territory screens and users

**Comment by fjlopez** [comment]
@lucenasj #won't fix is more appropriate, as you mention that this request cannot be fulfilled due to a TC decision.

**Comment by lucenasj** [comment]
Thanks @fjlopez

**Comment by fjlopez** [comment]
@lucenasj some of the issues moved today to the project board contain a #bug label but some of them may be an enhancement or can be old and collide with a TC decision. Feel free to remove the #bug label and update the label to #enhancement or #won't fix depending on the case.
