### ISSUE TITLE
Manage cartography styles

### ISSUE THREAD

**Issue by lucenasj** [sitmun/sitmun-admin-app#81]
Is required an expansión panel to manage cartography styles.

**Comment by fjlopez** [comment]
This is linked to https://github.com/sitmun/sitmun-backend-core/issues/121 because this issue depends on new features in the backend:

- [x] a boolean flag at the cartography level to notify clients that the cartography should be treated as a set of N cartographies, where N is the number of styles
- [x] a boolean flag at the cartography style level to mark the default cartography when the above flag is false.

**Comment by fjlopez** [comment]
@lucenasj done!

**Comment by gon-nexus** [comment]
Waiting https://github.com/sitmun/sitmun-backend-core/issues/126
