### ISSUE TITLE
SITMUN3 - Session

### ISSUE THREAD

**Issue by codinachssm** [sitmun/sitmun-admin-app#9]
Is there an expiration time-out for the session?

**Comment by montsemarco** [comment]
If there is a timeout for the session, maybe it would be nice to notify that fact to the user. 
For instance, Geonetwork notifies it with a multilingual pop-up at the top 
 
![timeoutAlert_Geonetwork](https://user-images.githubusercontent.com/1905272/107401769-7d86eb00-6b03-11eb-857d-0347792559e2.png)

**Comment by fjlopez** [comment]
@codinachssm @lucenasj The JWT credential that gives access to the backend has a validity that can be configured through the configuration property `security.authentication.jwt.token-validity-in-miliseconds` in the backend. The current value is `36000000` (10 hours), more or less a working day, but can be modified in the configuration file (`application.yml`). 

The backend will return 401 in most queries if the token used by the sitmun-admin-app expires. I think that if sitmun-admin-app detects such invalidation, it may open again the login form with a message explaining that the user must login again.

**Comment by codinachssm** [comment]
Ok, thnaks. Perhaps you could stablish the same default timeout as we have now at SITMUN2, instead of 10 hours. I don't know exactly which value we have now for the Administrator app but it's less than one hour (I don't know at which configuration file should I see it.)

**Comment by montsemarco** [comment]
sitmun2 is deployed in a Tomcat. 
If timeout is not defined neither in web.xml nor in code, I think that the context takes the Tomcat default session timeout (configured in  /conf/web.xml). I checked our Tomcat and we have the default value (30 minutes)

**Comment by fjlopez** [comment]
How timeout works in STM3 may differ form STM2 because the approach in STM2 was stateful (based on Tomcat Sessions) and in STM3 is stateless (based on JWT tokens). Implications:

- in STM2 if a user is inactive for longer than a time, the session is invalidated and requires a new authentication. That is, the session is active as long as you are working on it and you have a grace period of inactivity.
- in STM3 if when a user token expires, the user is required to request a new authentication. That is, the token gives you permission for accessing to the system for a time, independent of your activity.

So the behaviour is different. The method for having a behaviour in STM3 similar to the session timeout in STM2 is to limit the life of the token to, e.g., 30 minutes and to add to the backend a feature to refresh silently the JWT token, e.g.,  1 minute before the JWT token expires (e.g. `POST /api/authenticate/refresh-token`). 

When this feature is implemented, any app, such as the SITMUN administration, that detects the JWT token is getting old can request silently before the token expires to the backend a new JWT token (here is an example of such behaviour implemented in [Angular 9](https://jasonwatmore.com/post/2020/05/22/angular-9-jwt-authentication-with-refresh-tokens)).
